chat/urls.py
from django.urls import path, re_path


from .views import ThreadView, InboxView

app_name = 'chat'
urlpatterns = [
    path("", InboxView.as_view()),
    re_path(r"^(?P<username>[\w.@+-]+)", ThreadView.as_view()),
]

purechat/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView

from chat.views import UserView
from accounts.views import (
    login_view,
    logout_view,
    register_view,
)



urlpatterns = [
    path('', TemplateView.as_view(template_name="home.html")),
    path('login/', login_view),
    path('logout/', logout_view),
    path('register/', register_view),
    path('admin/', admin.site.urls),
    path('messages/', include('chat.urls')),
    path("discover/", UserView.as_view()),
]

accounts/models.py
from django.db import models

# Create your models here.

chat/models.py
from django.db import models

from django.conf import settings
from django.db import models
from django.db.models import Q


class ThreadManager(models.Manager):
    def by_user(self, user):
        qlookup = Q(first=user) | Q(second=user)
        qlookup2 = Q(first=user) & Q(second=user)
        qs = self.get_queryset().filter(qlookup).exclude(qlookup2).distinct()
        return qs

    def get_or_new(self, user, other_username): # get_or_create
        username = user.username
        if username == other_username:
            return None
        qlookup1 = Q(first__username=username) & Q(second__username=other_username)
        qlookup2 = Q(first__username=other_username) & Q(second__username=username)
        qs = self.get_queryset().filter(qlookup1 | qlookup2).distinct()
        if qs.count() == 1:
            return qs.first(), False
        elif qs.count() > 1:
            return qs.order_by('timestamp').first(), False
        else:
            Klass = user.__class__
            user2 = Klass.objects.get(username=other_username)
            if user != user2:
                obj = self.model(
                        first=user, 
                        second=user2
                    )
                obj.save()
                return obj, True
            return None, False


class Thread(models.Model):
    first        = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='chat_thread_first')
    second       = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='chat_thread_second')
    updated      = models.DateTimeField(auto_now=True)
    timestamp    = models.DateTimeField(auto_now_add=True)
    
    objects      = ThreadManager()

    @property
    def room_group_name(self):
        return f'chat_{self.id}'

    def broadcast(self, msg=None):
        if msg is not None:
            broadcast_msg_to_chat(msg, group_name=self.room_group_name, user='admin')
            return True
        return False


class ChatMessage(models.Model):
    thread      = models.ForeignKey(Thread, null=True, blank=True, on_delete=models.SET_NULL)
    user        = models.ForeignKey(settings.AUTH_USER_MODEL, verbose_name='sender', on_delete=models.CASCADE)
    message     = models.TextField()
    timestamp   = models.DateTimeField(auto_now_add=True)

chat/forms.py
from django import forms


class ComposeForm(forms.Form):
    message = forms.CharField(
            widget=forms.TextInput(
                attrs={"class": "form-control"}
                )
            )

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login, logout, authenticate
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
# Create your views here.

# Function based views to Class Based Views

def login_view(request, *args, **kwargs):
    form = AuthenticationForm(request, data=request.POST or None)
    if form.is_valid():
        user_ = form.get_user()
        login(request, user_)
        return redirect("/")
    context = {
        "form": form,
        "btn_label": "Login",
        "title": "Login"
    }
    return render(request, "accounts/auth.html", context)

def logout_view(request, *args, **kwargs):
    if request.method == "POST":
        logout(request)
        return redirect("/login")
    context = {
        "form": None,
        "description": "Are you sure you want to logout?",
        "btn_label": "Click to Confirm",
        "title": "Logout"
    }
    return render(request, "accounts/auth.html", context)


def register_view(request, *args, **kwargs):
    form = UserCreationForm(request.POST or None)
    if form.is_valid():
        user = form.save(commit=True)
        user.set_password(form.cleaned_data.get("password1"))
        # send a confirmation email to verify their account
        login(request, user)
        return redirect("/")
    context = {
        "form": form,
        "btn_label": "Register",
        "title": "Register"
    }
    return render(request, "accounts/auth.html", context)

chat/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import Http404, HttpResponseForbidden
from django.shortcuts import render
from django.urls import reverse
from django.views.generic.edit import FormMixin
from django.contrib.auth.models import User

from django.views.generic import DetailView, ListView

from .forms import ComposeForm
from .models import Thread, ChatMessage


class UserView(LoginRequiredMixin, ListView):
    template_name = 'chat/discover.html'
    def get_queryset(self):
        return User.objects.all()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        print(context)
        return context


class InboxView(LoginRequiredMixin, ListView):
    template_name = 'chat/inbox.html'
    def get_queryset(self):
        return Thread.objects.by_user(self.request.user)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        return context


class ThreadView(LoginRequiredMixin, FormMixin, DetailView):
    template_name = 'chat/thread.html'
    form_class = ComposeForm
    success_url = './'

    def get_queryset(self):
        return Thread.objects.by_user(self.request.user)

    def get_object(self):
        other_username = self.kwargs.get("username")
        obj, created = Thread.objects.get_or_new(self.request.user, other_username)
        if obj == None:
            raise Http404
        return obj

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['form'] = self.get_form()

        return context

    def post(self, request, *args, **kwargs):
        if not request.user.is_authenticated:
            return HttpResponseForbidden()
        self.object = self.get_object()
        form = self.get_form()
        if form.is_valid():
            return self.form_valid(form)
        else:
            return self.form_invalid(form)

    def form_valid(self, form):
        thread = self.get_object()
        user = self.request.user
        message = form.cleaned_data.get("message")
        ChatMessage.objects.create(user=user, thread=thread, message=message)
        return super().form_valid(form)

chat/templates/chat/discover.html
{% extends "base.html" %}

{% block content %}

<h3>Select a user to chat with</h3>

{% for i in object_list %}
    {% if i != user %}
        <p><a href='/messages/{{i}}#form'>{{i}}</a></p>
    {% endif %}
{% endfor %}

{% endblock %}

chat/templates/chat/inbox.html
{% extends "base.html" %}

{% block content %}
<p class='lead'>Hello {{user.username}}. This is your inbox</p>
{% for i in object_list %}
    <div class= 'container'>
        {% if user != object.first %}
            <div class='message-container' onclick="location.href='{{i.first}}#form'" style="cursor: pointer">
                <p><span class="left">{{ i.first }}</span></p>
                <br>
                {{ i.chatmessage_set.last.message }}
                <br>
                <p><span class="right">{{ i.chatmessage_set.last.timestamp }}</span></p>
            </div>
        {% else %}
            <div class='message-container' onclick="location.href='{{i.second}}#form'" style="cursor: pointer">
                <p><span class="left">{{ i.second }}</span></p>
                <br>
                {{ i.chatmessage_set.last.message }}
                <br>
                <p><span class="right">{{ i.chatmessage_set.last.timestamp }}</span></p>
            </div>
        {% endif %}
    </div>
{% endfor %}



{% endblock %}

chat/templates/chat/thread.html
{% extends "base.html" %}

{% block content %}
{% if user != object.first %}
  <p>Chat with {{ object.first }}</p>
{% else %}
  <p>Chat with {{ object.second }}</p>
{% endif %}
<ul id='chat-items'>
{% for chat in object.chatmessage_set.all %}
  {% if user == chat.user %}
    <div class='message-container darker'>
      <p><span class="left">{{ chat.user }}</span></p>
      <br>
      {{ chat.message }}
      <br>
      <p><span class="right">{{ chat.timestamp }}</span></p>
    </div>
  {% else %}
    <div class='message-container'>
      <p><span class="left">{{ chat.user }}</span></p>
      <br>
      {{ chat.message }}
      <br>
      <p><span class="right">{{ chat.timestamp }}</span></p>
    </div>
  {% endif %}

<!-- <li>{{ chat.message }} via {{ chat.user }}</li> -->

{% endfor %}
</ul>

<form id='form' method='POST' action=""> {% csrf_token %}
  <input type='hidden' id='myUsername' value='{{ user.username }}'/>
{{form.as_p }}
<input type='submit' class='btn btn-primary'/>
</form>
<br>
<br>

{% endblock %}

{% block script %}
<script src="https://cdnjs.cloudflare.com/ajax/libs/reconnecting-websocket/1.0.0/reconnecting-websocket.min.js"></script>
<script>
  //websocket scripts
  var loc = window.location
  var formData = $("#form")
  var msgInput = $("#id_message")
  var chatHolder = $("#chat-items")
  var me = $("#myUsername").val()
  
  var wsStart = 'ws://'
  if (loc.protocol == 'https:'){
    wsStart = 'wss://'
  }
  
  var endpoint = wsStart + loc.host + loc.pathname
  var socket = new ReconnectingWebSocket(endpoint)
  
  socket.onmessage = function(e){
    console.log('message', e)
    var chatDataMsg = JSON.parse(e.data)
    // chatHolder.append("<li>" + chatDataMsg.message + " via " + chatDataMsg.username + "</li>")
    var datetime = new Date().toLocaleString();
    if (chatDataMsg.username == me) {
      chatHolder.append("<div class='message-container darker'><p><span class='left'>" + me + "</span></p><br>" + chatDataMsg.message + "<br><p><span class='right'>" + datetime + "</span></p>")
    } else {
      chatHolder.append("<div class='message-container'><p><span class='left'>" + chatDataMsg.username + "</span></p><br>" + chatDataMsg.message + "<br><p><span class='right'>" + datetime + "</span></p>")
    }
    
  }
  socket.onopen = function(e){
    console.log('open', e)
    formData.submit(function(event){
      event.preventDefault()
      var msgText = msgInput.val()
      var finalData = {
        'message' : msgText
      }
      socket.send(JSON.stringify(finalData))
      formData[0].reset()
    })
  }
  socket.onerror = function(e){
    console.log('error', e)
  }
  socket.onclose = function(e){
    console.log('close', e)
  }
</script>
{% endblock %}

templates/accounts/auth.html
{% extends "base.html" %}


{% block content %}

<div class='col-10 col-md-4 mx-auto'>
    <h1>{{ title }}</h1>
    {% if description %}
    <p>{{ description }} </p>
    {% endif %}
    {% include "components/form.html" with form=form btn_label=btn_label %}

</div>

{% endblock content %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <title>Ignite Chat</title>
    {% include 'css.html' %}
    {% include "components/navbar.html" %}
    <style>
        .bg-purechat {
            background-color: #3e722e!important;
        }
        .message-container {
            border: 2px solid #dedede;
            background-color: #f1f1f1;
            border-radius: 5px;
            padding: 10px;
            margin: 10px 0;
            }
        .darker {
            border-color: #ccc;
            background-color: #ddd;
            }
        .right {
            float: right;
            color: #aaa;
            }
        .left {
            float: left;
            color: #999;
            }
      </style>
</head>
<body>
<br>
<br>
<div class='container'>
    <div class='row border-bottom my-3 py-3'>
        <div class='col'>
            <h1 class='p-0 m-0'>Ignite Chat</h1>
        </div>
    </div>
    {% block content %}
    {% endblock %}
</div>


{% include 'js.html' %}
{% block script %}
{% endblock %}

</body>
{% include "components/footer.html" %}
</html>

templates/components/form.html
<form method='POST'> {% csrf_token %}
    {{ form.as_p }}
    <button type='submit' class='btn btn-secondary'>{% if btn_label %}
        {{btn_label}} {% else %}Save{% endif %}</button>
</form>

templates/components/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark fixed-top bg-purechat mb-4">
    <a class="navbar-brand" href="/messages">Ignite</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
  
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav ml-auto">
        <li class="nav-item">
          <a class="nav-link" href="/messages">Inbox <span class="sr-only">(current)</span></a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="/discover">Discover <span class="sr-only">(current)</span></a>
        </li>
        {% if request.user.is_authenticated %}
        <li class="nav-item">
          <a class="nav-link" href="/logout">Logout</a>
        </li>
        
        {% else %}

          <li class="nav-item">
            <a class="nav-link" href="/login">Login</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="/register">Register</a>
          </li>

        {% endif %}
      
        
        
      </ul>
      <form class="form-inline my-2 my-lg-0 d-none">
        <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
      </form>
    </div>
  </nav>

templates/css.html
<!-- Bootstrap CSS -->
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css">

templates/home.html
{% extends "base.html" %}

{% block content %}

<p class='lead'>Hello {{user.username}}</p>
{% endblock %}

templates/js.html
 <!-- jQuery first, then Popper.js, then Bootstrap JS -->
<script
  src="//code.jquery.com/jquery-3.3.1.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"></script>
<script src="//stackpath.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>